index_data:
  - file_name: "Index CAC40 (FCHI) Entwicklung.csv"
    isin: "FR0003500008"
  - file_name: "Index DAX Entwicklung.csv"
    isin: "DE0008469008"
  - file_name: "Index Dow Jones (DJI) Entwicklung.csv"
    isin: "US2605661048"
  - file_name: "Index Euronext 100 (N100) Entwicklung.csv"
    isin: "FR0003502079"
  - file_name: "Index S&P500 Entwicklung.csv"
    isin: "US78378X1072"